/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminLayout: typeof import('./components/layout/AdminLayout.vue')['default']
    AiOutput: typeof import('./components/court/AiOutput.vue')['default']
    BangbooAssistant: typeof import('./components/bangboo/BangbooAssistant.vue')['default']
    BangbooAvatar: typeof import('./components/bangboo/BangbooAvatar.vue')['default']
    BangbooChat: typeof import('./components/bangboo/BangbooChat.vue')['default']
    BangbooState: typeof import('./components/common/BangbooState.vue')['default']
    CertGateDialog: typeof import('./components/common/CertGateDialog.vue')['default']
    DifficultyBadge: typeof import('./components/task/DifficultyBadge.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRate: typeof import('element-plus/es')['ElRate']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    EmptyState: typeof import('./components/common/EmptyState.vue')['default']
    FileUpload: typeof import('./components/common/FileUpload.vue')['default']
    HunterLevelBadge: typeof import('./components/hunter/HunterLevelBadge.vue')['default']
    MainLayout: typeof import('./components/layout/MainLayout.vue')['default']
    PageBackButton: typeof import('./components/common/PageBackButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusTag: typeof import('./components/common/StatusTag.vue')['default']
    TaskCard: typeof import('./components/task/TaskCard.vue')['default']
    TaskCardSkeleton: typeof import('./components/task/TaskCardSkeleton.vue')['default']
    TaskFilter: typeof import('./components/task/TaskFilter.vue')['default']
    VoteBar: typeof import('./components/court/VoteBar.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
