/**
 * mockData.ts — 开发期 Mock 数据
 * 仅在 API 尚未就绪 / 网络不通时作为公开页面的展示兜底
 * 生产环境不引用此文件
 */
import type { TaskVO } from '@/types/task'
import type { LeaderboardEntryVO } from '@/types/user'
import { TASK_COVERS } from '@/assets'

export const MOCK_HOT_TASKS: TaskVO[] = [
  {
    id: 1001,
    title: '帮取外卖，付双倍跑腿费',
    description: '宿舍楼下取一份外卖，送到 B4-312，限30分钟内。',
    category: 'ERRAND',
    categoryName: '跑腿代办',
    difficulty: 'F',
    bountyAmount: 15,
    bountyType: 'CASH',
    location: '南门食堂',
    deadline: new Date(Date.now() + 1000 * 60 * 35).toISOString(),
    completionStandard: '放到门口，拍照确认',
    evidenceRequirement: '取餐截图 + 送达照片',
    status: 'PUBLISHED',
    statusName: '招募中',
    publisherId: 101,
    publisherName: '陆星辰',
    publisherAvatar: undefined,
    assignedHunterId: undefined,
    coverImageUrl: TASK_COVERS.coffee,
    applicationCount: 3,
    isFavorited: false,
    viewCount: 42,
    createdAt: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
    publishedAt: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
  },
  {
    id: 1002,
    title: '数学分析 A 卷辅导，期末速成',
    description: '期末周，需要有人给我讲一遍极限与连续，最好有实战例题，2小时够不够？',
    category: 'STUDY',
    categoryName: '学习互助',
    difficulty: 'B',
    bountyAmount: 80,
    bountyType: 'CASH',
    location: '图书馆三楼',
    deadline: new Date(Date.now() + 1000 * 60 * 60 * 48).toISOString(),
    completionStandard: '能独立解出三道典型题',
    evidenceRequirement: '辅导记录截图',
    status: 'PUBLISHED',
    statusName: '招募中',
    publisherId: 102,
    publisherName: '叶明宇',
    publisherAvatar: undefined,
    assignedHunterId: undefined,
    coverImageUrl: TASK_COVERS.mathCram,
    applicationCount: 1,
    isFavorited: false,
    viewCount: 87,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
  },
  {
    id: 1003,
    title: '社团宣传海报设计，要有朋克感',
    description: '游戏社招新，需要一张 A3 海报 + 配套小红书尺寸图，交出格式：PSD + PNG。',
    category: 'DESIGN',
    categoryName: '设计创作',
    difficulty: 'C',
    bountyAmount: 200,
    bountyType: 'CASH',
    location: '线上',
    deadline: new Date(Date.now() + 1000 * 60 * 60 * 72).toISOString(),
    completionStandard: '按需求稿完成，修改两轮',
    evidenceRequirement: '最终稿文件',
    status: 'PUBLISHED',
    statusName: '招募中',
    publisherId: 103,
    publisherName: '苏可茵',
    publisherAvatar: undefined,
    assignedHunterId: undefined,
    coverImageUrl: TASK_COVERS.lightStripRepair,
    applicationCount: 5,
    isFavorited: true,
    viewCount: 213,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
  },
  {
    id: 1004,
    title: '实验室设备出现问题，懂电路的来',
    description: '示波器无法正常显示，可能是探头或接地问题，需要现场排查。',
    category: 'REPAIR',
    categoryName: '维修协助',
    difficulty: 'A',
    bountyAmount: 60,
    bountyType: 'CASH',
    location: '工科楼 505',
    deadline: new Date(Date.now() + 1000 * 60 * 60 * 6).toISOString(),
    completionStandard: '设备恢复正常显示',
    evidenceRequirement: '修复后运行视频',
    status: 'PUBLISHED',
    statusName: '招募中',
    publisherId: 104,
    publisherName: '方恒毅',
    publisherAvatar: undefined,
    assignedHunterId: undefined,
    coverImageUrl: undefined,
    applicationCount: 0,
    isFavorited: false,
    viewCount: 34,
    createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    publishedAt: new Date(Date.now() - 1000 * 60 * 28).toISOString(),
  },
  {
    id: 1005,
    title: '毕业典礼志愿者，全天跑场',
    description: '6月底毕业典礼需要4名志愿者协助引导工作，有餐盒+证书，算分的。',
    category: 'ACTIVITY',
    categoryName: '活动协助',
    difficulty: 'F',
    bountyAmount: 0,
    bountyType: 'OFFLINE',
    location: '体育馆',
    deadline: new Date(Date.now() + 1000 * 60 * 60 * 120).toISOString(),
    completionStandard: '全程出勤签到',
    evidenceRequirement: '现场签到表',
    status: 'PUBLISHED',
    statusName: '招募中',
    publisherId: 105,
    publisherName: '校学生会',
    publisherAvatar: undefined,
    assignedHunterId: undefined,
    coverImageUrl: undefined,
    applicationCount: 9,
    isFavorited: false,
    viewCount: 501,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
  {
    id: 1006,
    title: '论文致谢写作，要真实不矫情',
    description: '帮我润色毕业论文致谢，现有草稿 500 字，保留我的语气，但让它读起来更有分量。',
    category: 'COPYWRITING',
    categoryName: '文案写作',
    difficulty: 'B',
    bountyAmount: 50,
    bountyType: 'CASH',
    location: '线上',
    deadline: new Date(Date.now() + 1000 * 60 * 60 * 36).toISOString(),
    completionStandard: '符合风格且通过导师审阅',
    evidenceRequirement: '最终 Word 文档',
    status: 'PUBLISHED',
    statusName: '招募中',
    publisherId: 106,
    publisherName: '陈佳怡',
    publisherAvatar: undefined,
    assignedHunterId: undefined,
    coverImageUrl: undefined,
    applicationCount: 2,
    isFavorited: false,
    viewCount: 128,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
  },
]

export const MOCK_LEADERBOARD: LeaderboardEntryVO[] = [
  {
    rank: 1,
    userId: 3,
    nickname: '林野',
    level: 4,
    title: '风纪猎人',
    xp: 1280,
    completedTaskCount: 12,
    reputation: 960,
  },
  {
    rank: 2,
    userId: 4,
    nickname: '周暮',
    level: 3,
    title: '夜行跑腿王',
    xp: 1040,
    completedTaskCount: 8,
    reputation: 930,
  },
  {
    rank: 3,
    userId: 5,
    nickname: '许知遥',
    level: 2,
    title: '学习支援员',
    xp: 860,
    completedTaskCount: 7,
    reputation: 910,
  },
  {
    rank: 4,
    userId: 6,
    nickname: '沈川',
    level: 2,
    title: '维修协作员',
    xp: 720,
    completedTaskCount: 5,
    reputation: 880,
  },
  {
    rank: 5,
    userId: 7,
    nickname: '白一禾',
    level: 1,
    title: '设计接线员',
    xp: 560,
    completedTaskCount: 4,
    reputation: 850,
  },
]
