import { expect, test, type Locator } from '@playwright/test'
import { asUser, expectNoClientCrash, expectToast, expectUrl } from './helpers'

async function clickCentered(locator: Locator) {
  await locator.evaluate((element) => element.scrollIntoView({ block: 'center', inline: 'nearest' }))
  const box = await locator.boundingBox()
  await locator.click({ position: { x: 8, y: Math.max(1, (box?.height ?? 32) / 2) } })
}

test.describe('申请管理、我的任务、契约履约与评价回归', () => {
  test('委托人可选择或拒绝申请，非委托人不可查看申请列表', async ({ browser }) => {
    const outsiderContext = await browser.newContext()
    const outsider = await outsiderContext.newPage()
    await asUser(outsider, 'hunter01')
    await outsider.goto('/tasks/101/applications')
    await expectToast(outsider, '只有委托人可查看申请列表')
    await expect(outsider.locator('body')).toContainText('谁来接这单')
    await expectNoClientCrash(outsider)
    await outsiderContext.close()

    const rejectContext = await browser.newContext()
    const rejectPage = await rejectContext.newPage()
    await asUser(rejectPage, 'client01')
    await rejectPage.goto('/tasks/101/applications')
    await expect(rejectPage.locator('body')).toContainText('申请管理')
    await expect(rejectPage.locator('body')).toContainText('安比猎人')
    await clickCentered(rejectPage.getByRole('button', { name: '拒绝' }).first())
    await rejectPage.getByRole('button', { name: '确认拒绝' }).click()
    await expectToast(rejectPage, '已拒绝该申请')
    await expectNoClientCrash(rejectPage)
    await rejectContext.close()

    const acceptContext = await browser.newContext()
    const acceptPage = await acceptContext.newPage()
    await asUser(acceptPage, 'client01')
    await acceptPage.goto('/tasks/102/applications')
    await expect(acceptPage.locator('body')).toContainText('铃音猎人')
    await acceptPage.getByRole('button', { name: '选择该猎人' }).first().click()
    await acceptPage.getByRole('button', { name: '确认选择' }).click()
    await expectToast(acceptPage, '已选定猎人，契约已生成')
    await expectUrl(acceptPage, /\/contracts\/\d+/)
    await expect(acceptPage.locator('body')).toContainText('履约契约')
    await expectNoClientCrash(acceptPage)
    await acceptContext.close()
  })

  test('我的任务三类列表、申请修改撤销与入口跳转可用', async ({ page }) => {
    await asUser(page, 'hunter02')
    await page.goto('/my-tasks')
    await expect(page.locator('body')).toContainText('我的任务簿')
    await expect(page.getByRole('tab', { name: /我发布的/ })).toBeVisible()

    await page.getByRole('tab', { name: /我的申请/ }).click()
    await expect(page.locator('body')).toContainText('帮我取南门咖啡')
    await page.getByRole('button', { name: '修改' }).first().click()
    await expect(page.locator('.el-dialog')).toContainText('修改申请')
    await page.getByPlaceholder('说说你为什么适合接这单').fill('E2E 修改申请说明')
    await page.getByRole('button', { name: '保存修改' }).click()
    await expectToast(page, '申请已更新')

    await page.getByRole('button', { name: '撤销' }).first().click()
    await page.getByRole('button', { name: '确认撤销' }).click()
    await expectToast(page, '申请已撤销')
    await expectNoClientCrash(page)

    const hunter = await page.context().newPage()
    await asUser(hunter, 'hunter01')
    await hunter.goto('/my-tasks')
    await hunter.getByRole('tab', { name: /我承接的/ }).click()
    await expect(hunter.locator('body')).toContainText('实验报告 LaTeX 排版修复')
    await hunter.locator('.mine-row', { hasText: '实验报告 LaTeX 排版修复' }).click()
    await expectUrl(hunter, /\/contracts\/301/)
    await expect(hunter.locator('body')).toContainText('实验报告 LaTeX 排版修复')
    await expectNoClientCrash(hunter)
  })

  test('契约双方权限、证据空提交、履约确认、取消和评价状态正确', async ({ browser }) => {
    const outsiderContext = await browser.newContext()
    const outsider = await outsiderContext.newPage()
    await asUser(outsider, 'hunter02')
    await outsider.goto('/contracts/301')
    await expectToast(outsider, '非任务双方不能查看契约')
    await expect(outsider.locator('body')).toContainText('NO SIGNAL')
    await expectNoClientCrash(outsider)
    await outsiderContext.close()

    const hunterContext = await browser.newContext()
    const hunter = await hunterContext.newPage()
    await asUser(hunter, 'hunter01')
    await hunter.goto('/contracts/301')
    await expect(hunter.locator('body')).toContainText('履约契约')
    await hunter.getByRole('button', { name: '提交履约证据' }).click()
    await hunter.getByRole('button', { name: '提交证据' }).click()
    await expectToast(hunter, '请上传文件或填写说明')
    await hunter.getByRole('textbox', { name: '说明' }).fill('E2E：已修复 LaTeX 模板并交付说明。')
    await hunter.getByRole('button', { name: '提交证据' }).click()
    await expectToast(hunter, '证据已提交')
    await hunter.getByRole('button', { name: '提交完成' }).click()
    await hunter.getByRole('button', { name: '提交', exact: true }).click()
    await expectToast(hunter, '已提交，等待委托人确认')
    await expectNoClientCrash(hunter)

    const clientContext = await browser.newContext()
    const client = await clientContext.newPage()
    await asUser(client, 'client01')
    await client.goto('/contracts/302')
    await expect(client.locator('body')).toContainText('待确认')
    await client.getByRole('button', { name: '确认完成' }).click()
    await client.getByRole('button', { name: '确认完成' }).last().click()
    await expectToast(client, '已确认完成，赏金已结算')
    await expectNoClientCrash(client)

    await client.goto('/contracts/303')
    await expect(client.getByRole('button', { name: '评价对方' })).toBeVisible()
    await client.getByRole('button', { name: '评价对方' }).click()
    await client.getByPlaceholder('说说这次合作的体验').fill('E2E：交付清楚，沟通及时。')
    await client.getByRole('button', { name: '提交评价' }).click()
    await expectToast(client, '评价已提交')
    await expect(client.getByRole('button', { name: '评价对方' })).toHaveCount(0)

    await hunter.goto('/contracts/302')
    await hunter.getByRole('button', { name: '取消契约' }).click()
    await hunter.getByRole('textbox', { name: '取消原因' }).fill('')
    await hunter.getByRole('button', { name: '确认取消' }).click()
    await expectToast(hunter, '请填写取消原因')
    await hunter.getByRole('textbox', { name: '取消原因' }).fill('E2E 协商取消')
    await hunter.getByRole('button', { name: '确认取消' }).click()
    await expectToast(hunter, '契约已取消')
    await expect(hunter.locator('body')).toContainText('已取消')

    await hunterContext.close()
    await clientContext.close()
  })
})
