import { expect, test } from '@playwright/test'
import { asUser, expectNoClientCrash, expectToast, expectUrl } from './helpers'

test.describe('小法庭与后台治理回归', () => {
  test('小法庭当事人陈述/举证、AI 摘要点评、投票权限和重复投票可回归', async ({ browser }) => {
    const clientContext = await browser.newContext()
    const client = await clientContext.newPage()
    await asUser(client, 'client01')
    await client.goto('/court/401')
    await expect(client.locator('body')).toContainText('案件裁决')
    await expect(client.locator('body')).toContainText('字幕校对交付范围争议')

    await client.getByPlaceholder('作为当事人补充你的陈述').fill('E2E：委托方补充陈述，要求核对错别字列表。')
    await client.getByRole('button', { name: '提交陈述' }).click()
    await expectToast(client, '陈述已提交')

    await client.getByPlaceholder('补充证据说明（可选）').fill('E2E：补充文字证据。')
    await client.getByRole('button', { name: '呈递证据' }).click()
    await expectToast(client, '证据已呈递')

    await expect(client.locator('body')).toContainText('委托方关注错别字残留')
    await expect(client.locator('body')).toContainText('这不是谁嗓门大谁赢')

    await client.getByRole('button', { name: '建议和解' }).click()
    await client.getByRole('button', { name: '投出我的一票' }).click()
    await expectToast(client, '案件双方不能作为陪审员投票')
    await expectNoClientCrash(client)
    await clientContext.close()

    const juryContext = await browser.newContext()
    const jury = await juryContext.newPage()
    await asUser(jury, 'jury01')
    await jury.goto('/court/401')
    await expect(jury.locator('body')).toContainText('你已投出庄严一票')
    await expect(jury.locator('body')).toContainText('舆论风向')
    await expectNoClientCrash(jury)
    await juryContext.close()

    const newCaseContext = await browser.newContext()
    const casePage = await newCaseContext.newPage()
    await asUser(casePage, 'client01')
    await casePage.goto('/contracts/302')
    await casePage.getByRole('button', { name: '发起小法庭' }).click()
    await casePage.getByLabel('案件标题').fill('E2E 新纠纷')
    await casePage.getByLabel('陈述内容').fill('E2E：对交付范围存在争议。')
    await casePage.getByRole('button', { name: '发起仲裁' }).click()
    await expectToast(casePage, '已发起小法庭')
    await expectUrl(casePage, /\/court\/\d+/)
    await expectNoClientCrash(casePage)
    await newCaseContext.close()
  })

  test('后台看板、用户封禁、任务审核、认证审核、运营配置和审计日志可回归', async ({ page }) => {
    await asUser(page, 'admin')

    await page.goto('/admin/dashboard')
    await expect(page.locator('body')).toContainText('公会运营看板')
    await expect(page.locator('body')).toContainText('用户总数')
    await expectNoClientCrash(page)

    await page.goto('/admin/users')
    await expect(page.locator('body')).toContainText('用户管理')
    await page.getByPlaceholder('搜索用户名 / 昵称').fill('newbie')
    await page.getByRole('button', { name: '搜索' }).click()
    await page.getByRole('row', { name: /newbie/ }).getByRole('button', { name: /^封禁$/ }).click()
    await page.getByPlaceholder('例如：违反公会规约、恶意刷单…').fill('E2E 封禁验证')
    await page.getByRole('button', { name: '确认封禁' }).click()
    await expectToast(page, '已封禁该用户')
    await page.getByRole('button', { name: '已封禁', exact: true }).click()
    await page.getByPlaceholder('搜索用户名 / 昵称').fill('newbie')
    await page.getByRole('button', { name: '搜索' }).click()
    await page.getByRole('row', { name: /newbie/ }).getByRole('button', { name: /^解封$/ }).click()
    await page.getByRole('button', { name: '确认解封' }).click()
    await expectToast(page, '已解封该用户')

    await page.goto('/admin/tasks')
    await expect(page.locator('body')).toContainText('任务审核')
    await page.getByRole('row', { name: /社团招新海报设计/ }).getByRole('button', { name: '通过' }).click()
    await expectToast(page, '已通过任务《社团招新海报设计，今晚给初稿》')

    await page.getByPlaceholder('搜索任务标题').fill('疑似违规')
    await page.getByPlaceholder('搜索任务标题').press('Enter')
    await page.getByRole('row', { name: /疑似违规/ }).getByRole('button', { name: '驳回' }).click()
    await page.getByPlaceholder('例如：任务描述不清晰或涉及违规内容，请修改后重新提交').fill('E2E 驳回违规任务')
    await page.getByRole('button', { name: '确认驳回' }).click()
    await expectToast(page, '已驳回任务《疑似违规：代写整篇课程论文》')

    await page.goto('/admin/certifications')
    await expect(page.locator('body')).toContainText('校园认证审核')
    await page.getByRole('row', { name: /待审新人/ }).getByRole('button', { name: '通过' }).click()
    await expectToast(page, /已通过 .* 的认证/)

    await page.goto('/admin/ops-config')
    await expect(page.locator('body')).toContainText('运营配置与内容安全')
    await page.getByPlaceholder('输入关键词').fill('E2E违规词')
    await page.getByRole('button', { name: '加入' }).click()
    await expect(page.locator('.keyword-list')).toContainText('E2E违规词')
    await page.getByRole('button', { name: '保存配置' }).click()
    await expectToast(page, '运营配置已保存')

    await page.goto('/admin/court-cases')
    await expect(page.locator('body')).toContainText('案件裁决')
    await page.getByRole('row', { name: /字幕校对交付范围争议/ }).getByRole('button').first().click()
    const drawer = page.locator('.el-drawer')
    await expect(drawer).toContainText('双方陈述')
    await expect(drawer).toContainText('裁决结果')
    await drawer.getByRole('button', { name: '落 槌 裁 决' }).click()
    await drawer.getByPlaceholder('请阐述裁决依据与判定逻辑，将公示给双方与陪审团').fill('E2E：按证据链部分支持猎人。')
    await drawer.getByText('归档为判例（供后续类似纠纷参考）').click()
    await drawer.getByRole('button', { name: '落 槌 裁 决' }).click()
    await page.getByRole('button', { name: '确认裁决' }).click()
    await expectToast(page, '裁决已落槌')

    await page.goto('/admin/audit-logs')
    await expect(page.locator('body')).toContainText('审计日志')
    await expect(page.locator('body')).toContainText('TASK_REVIEW_QUEUE')
    await expect(page.locator('body')).toContainText('CONTENT_BLOCKED')
    await expectNoClientCrash(page)
  })
})
